--시퀀스를 생성할 때에는 'SEQ_'로 시작하는 것이 일반적입니다.
CREATE SEQUENCE SEQ_T_BOARD;

--테이블 생성시 'TBL_'로 시작하거나 'T_'와 같이 시작하는 것이 일반적입니다.
CREATE TABLE T_BOARD(
	BNO NUMBER(10),
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	WRITER VARCHAR2(100) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE,
	CONSTRAINT PK_T_BOARD PRIMARY KEY(BNO)
);

--더미 데이터 (테이블 생성시 넣는 의미 없느 ㄴ데이터를 토이 데이터(toy data) 혹은 더미 데이터(dummy data)라고 합니다.
INSERT INTO T_BOARD (BNO, TITLE, CONTENT, WRITER)
VALUES (SEQ_T_BOARD.NEXTVAL, '제목 테스트4', '내용 테스트4', 'user03');

SELECT * FROM T_BOARD;

CREATE TABLE T_FILE (
	BNO NUMBER(10),
	FILENAME VARCHAR2(2000),
	FILEPATH VARCHAR2(2000),
	CONSTRAINT FK_BNO FOREIGN KEY (BNO) REFERENCES T_BOARD(BNO)
);


SELECT * FROM T_FILE;

CREATE SEQUENCE SEQ_T_REPLY;

CREATE TABLE T_REPLY (
	RNO NUMBER(10),
	BNO NUMBER(10) NOT NULL,
	REPLY VARCHAR2(2000) NOT NULL,
	REPLYER VARCHAR2(100) NOT NULL,
	REPLYDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE
);

SELECT * FROM t_board;
INSERT INTO T_REPLY (RNO, BNO, REPLY, REPLYER)
VALUES (SEQ_T_REPLY.NEXTVAL, 155, '댓글 제목', '댓글 작성자');
INSERT INTO T_REPLY (RNO, BNO, REPLY, REPLYER)
(SELECT SEQ_T_REPLY.NEXTVAL, BNO, REPLY, REPLYER FROM T_REPLY WHERE BNO = 155);